spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:/Users/seungbin/Desktop/git/spring-batch/db/test;AUTO_SERVER=TRUE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: always